namespace ButtonGame.Stats.Enums
{
    public enum Stat
    {
        Name,
        Health,
        Mana,
        ManaRegen,
        AttackPower,
        Damage,
        Defense,
        EnrageDefense,
        AttackSpeed,
        BlockAmount,
        CritFactor,
        CritDamage,
        CritResist,
        EnrageCritDamage,
        CooldownReduction,
        HealingReceived,
        Description,
        IdleTime,
        DamageReduction,
        EnrageDamageReduction,
        IsBoss,
        DropTier,
        DropChance,
        TimeLimit,
        Capacity,
        Spirit,
        HealingPower,
        Proficiency,
        Confidence,
        Greed,
        FatDesire,
        Metabolism
    }
}
