namespace ButtonGame.Stats
{
    public enum Stat
    {
        Name,
        Health,
        Mana,
        ManaRegen,
        AttackPower,
        Defense,
        EnrageDefense,
        AttackSpeed,
        BlockAmount,
        CritFactor,
        CritDamage,
        CritResist,
        EnrageCritDamage,
        CooldownReduction,
        DynamicCDR,
        HealingReceived,
        Description,
        IdleTime,
        DamageReduction,
        EnrageDamageReduction,
        IsBoss,
        DropTier,
        DropChance,
        TimeLimit
    }
}
